### PR TITLE
Merge to master

### PR DESCRIPTION
**Pull request by JTOne123**

### CODE REVIEW

**Comment by CherechesC** [comment]
Can you please let me know why you want to merge this in my repo? Thanks.

**Comment by JTOne123** [comment]
Really I don't know, I thought it will give sense. If you are disagree I will close the pull request

**Comment by CherechesC** [comment]
I've been away for a few weeks with limited internet connection, this is why I did not reply. For the moment, I don't have the time to actively develop this extension, and I also don't think there is any reason to have 2 extensions published in the VS marketplace. 

I don't think you need to continue to push your changes to this repo, as I won't update the extension that I have published.

**Comment by JTOne123** [comment]
Hi Cristian, I have thought about it also and I agree with you!

**Pull request closed without merging**
